services:
  - type: web
    name: nyc-crime-visual
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: preswald run
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
